/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.btm.budget.ihm;

/**
 *
 * @author sdalens
 */
public class test extends javax.swing.JPanel {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        yearText = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        canvas2 = new java.awt.Canvas();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ImageLeft");
        add(jLabel1, new java.awt.GridBagConstraints());

        yearText.setText("Year");
        jScrollPane1.setViewportView(yearText);

        add(jScrollPane1, new java.awt.GridBagConstraints());

        jLabel2.setText("ImageRigth");
        add(jLabel2, new java.awt.GridBagConstraints());
        add(canvas1, new java.awt.GridBagConstraints());
        add(canvas2, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private java.awt.Canvas canvas2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane yearText;
    // End of variables declaration//GEN-END:variables
}
